//comment 1
//comment 2
//comment 3
//comment 4
//comment 5
//comment 6
//comment 7
//comment 8
//comment 9
//comment 10
//comment 11
//comment 12
//comment 13
//commennt 14
//comment 1
//comment 2
//comment 3
//comment 4
//comment 5
//comment 6
import java.io.*;
import java.util.*;
 class Node{
     int key;
         String data;
             public Node(int key, String data){
                     this.key = key;
                             this.data=data;
                                 }
                                  }
                                  public class timeMethods {
                                      public static int N=32654;
                                          public static Node[] records;
                                              public static Node[] sortedRecords;
                                                  public static int[] searchKeys;
                                                      
                                                          public static void main(String args []) throws Exception{
                                                                  records = readFile("ulysses.numbered");
                                                                          sortedRecords = records.clone();

                                                                                  Arrays.sort(sortedRecords, Comparator.comparingInt(n->n.key));
                                                                                          int repetitions = 30;

                                                                                                  double linearTotal = 0;
                                                                                                          double linearTotalSq =0;
                                                                                                                  
                                                                                                                          double binaryTotal = 0;
                                                                                                                                  double binaryTotalSq = 0;

                                                                                                                                          for(int r=0;r<repetitons;r++){
                                                                                                                                                      generateRandomKeys(30);

                                                                                                                                                                  long start = System.nanoTime();

                                                                                                                                                                              for(int key:searchKeys){
                                                                                                                                                                                              linearSearch(records,key);
                                                                                                                                                                                                          }
                                                                                                                                                                                                                      long finish = System.nanoTime();
                                                                                                                                                                                                                                  double linearTime = (finish-start)/1e6;

                                                                                                                                                                                                                                              linearTotal += linearTime;
                                                                                                                                                                                                                                                          linearTotalSq += linearTime * linearTime;

                                                                                                                                                                                                                                                                      start=System.nanoTime();
                                                                                                                                                                                                                                                                                  for(int key:searchKeys){
                                                                                                                                                                                                                                                                                                  binarySearch(sortedRecords,key);
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                          finish = System.nanoTime();
                                                                                                                                                                                                                                                                                                                                      double binaryTime = (finish-start)/1e6;

                                                                                                                                                                                                                                                                                                                                                  binaryTotal += binaryTime;
                                                                                                                                                                                                                                                                                                                                                              binaryTotalSq += binaryTime * binaryTime;
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                              double linearAvg = linearTotal/repetitions;
                                                                                                                                                                                                                                                                                                                                                                                      double linearStd = Math.sqrt(linearTotalSq-repetitions*linearAvg*linearAvg)/(repetitions-1);
                                                                                                                                                                                                                                                                                                                                                                                              double binaryAvg = binaryTotal/repetitions;
                                                                                                                                                                                                                                                                                                                                                                                                      double binaryStd = Math.sqrt(binaryTotalSq-repetitions*binaryAvg*binaryAvg)/(repetitions-1);
                                                                                                                                                                                                                                                                                                                                                                                                              

                                                                                                                                                                                                                                                                                                                                                                                                                      System.out.println("\nResults");
                                                                                                                                                                                                                                                                                                                                                                                                                              System.out.println("Linear Search");
                                                                                                                                                                                                                                                                                                                                                                                                                                      System.out.println("Average time = " + linearAvg +"ms");
                                                                                                                                                                                                                                                                                                                                                                                                                                              System.out.println("Std deviation = " + linearStd + "ms");
                                                                                                                                                                                                                                                                                                                                                                                                                                                      System.out.println();
                                                                                                                                                                                                                                                                                                                                                                                                                                                              System.out.println("Binary Search");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      System.out.println("Average time= " + binaryAvg + "ms");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              System.out.println("Std deviation =" + binaryStd + "ms");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              static Node[] readFile(String filename) throws Exception{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          BufferedReader br = new
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      BufferedReader(new FileReader(filename));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ArrayList<Node.list = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              String line;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          while((line =br.readLine())!=null){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          String [] parts = line.split("",2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          int key = Integer.parseInt(parts[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          String data = parts.length >1? parts[1]: "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          list.add(new Node(key,data));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  br.close();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return list.toArray(new Node[0]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          static void generateRandomKeys(int count){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          searchKeys = new int[count];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Random rand = new Randpom();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for(int i=0;i<count;i++){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              searchKeys[i]= rand.nextInt(32654) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      static Node linearSearch(Node[] arr,int key){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for(Node n:arr){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(n!= null && n.key == key)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return n;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      static Node binarySearch(Node[] arr,int key){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      int low=0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      int high = arr.length-1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      while(low<=high){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          int mid=(low +high)/2;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(arr[mid].key == key)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return arr[mid];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else if(arr[mid].key<key)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              low = mid+1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  else 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        high = mid-1; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
